version: "3.9"

networks:
  nango:
  proxy_net:
    external: true   # Coolify's external proxy network (same one keycloak uses)
    name: a8sk8cg0swg0ww0w0ogoowog  # map to the actual existing Docker network name

volumes:
  nango_db_data:

services:
  nango-db:
    image: postgres:16.0-alpine
    container_name: nango-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${NANGO_DB_USER:-nango}
      POSTGRES_PASSWORD: ${NANGO_DB_PASSWORD:-nango}
      POSTGRES_DB: ${NANGO_DB_NAME:-nango}
    volumes:
      - nango_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NANGO_DB_USER:-nango} -d ${NANGO_DB_NAME:-nango}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - nango

  nango-redis:
    image: redis:7.2.4
    container_name: nango-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - nango

  nango-server:
    image: nangohq/nango-server:hosted-0.67.0
    container_name: nango-server
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      nango-db:
        condition: service_healthy
      nango-redis:
        condition: service_healthy
    environment:
      # Networking / bind
      SERVER_PORT: 3003
      NANGO_CONNECT_UI_PORT: 3009
      SERVER_HOST: 0.0.0.0
      NANGO_SERVER_HOST: 0.0.0.0
      HOST: 0.0.0.0

      # Required secrets
      NANGO_ENCRYPTION_KEY: ${NANGO_ENCRYPTION_KEY}
      NANGO_SECRET_KEY: ${NANGO_SECRET_KEY}

      # Database
      NANGO_DB_HOST: nango-db
      NANGO_DB_USER: nango
      NANGO_DB_PASSWORD: super-secret
      NANGO_DB_NAME: nango
      NANGO_DB_SSL: false
      NANGO_DB_POOL_MIN: 2
      NANGO_DB_POOL_MAX: 10
      RECORDS_DATABASE_URL: postgresql://nango:super-secret@nango-db:5432/nango

      # Public URLs (Traefik handles TLS)
      NANGO_SERVER_URL: https://nango.csa.competera.com
      NANGO_PUBLIC_SERVER_URL: https://nango.csa.competera.com
      NANGO_PUBLIC_CONNECT_URL: https://nango.csa.competera.com/connect
      NANGO_SERVER_WEBSOCKETS_PATH: /socket

      # Dashboard auth
      FLAG_AUTH_ENABLED: true
      NANGO_DASHBOARD_USERNAME: admin
      NANGO_DASHBOARD_PASSWORD: ${NANGO_DASHBOARD_PASSWORD}

      # Connect UI
      FLAG_SERVE_CONNECT_UI: true

      # Logging
      LOG_LEVEL: info
      NANGO_LOGS_ENABLED: false
      NANGO_LOGS_ES_URL: http://nango-elasticsearch:9200
      NANGO_LOGS_ES_USER: ""
      NANGO_LOGS_ES_PWD: ""

      # Security / CORS
      ALLOW_CORS_ORIGIN: "[*]"
      ALLOW_IFRAME_ORIGIN: "[*]"
      # removed CSP_REPORT_ONLY (Coolify error)

    volumes:
      - ./packages/providers/providers.yaml:/packages/providers/providers.yaml:ro

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3003/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

    networks:
      - nango
      - proxy_net

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=a8sk8cg0swg0ww0w0ogoowog"

      # --- Plain HTTP router that actually forwards to the app (no TLS) ---
      # This gives ACME a clean path and proves the router matches.
      - "traefik.http.routers.nango-http.rule=Host(`nango.csa.competera.com`)"
      - "traefik.http.routers.nango-http.entrypoints=http"
      - "traefik.http.routers.nango-http.tls=false"
      - "traefik.http.routers.nango-http.service=nango"

      # --- HTTPS API (3003) ---
      - "traefik.http.routers.nango.rule=Host(`nango.csa.competera.com`)"
      - "traefik.http.routers.nango.entrypoints=https"
      - "traefik.http.routers.nango.tls=true"
      - "traefik.http.routers.nango.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nango.service=nango"

      # --- HTTPS Connect UI at /connect (3009) ---
      - "traefik.http.routers.nango-connect.rule=Host(`nango.csa.competera.com`) && PathPrefix(`/connect`)"
      - "traefik.http.routers.nango-connect.entrypoints=https"
      - "traefik.http.routers.nango-connect.tls=true"
      - "traefik.http.routers.nango-connect.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nango-connect.service=nango-connect"

      # Backends
      - "traefik.http.services.nango.loadbalancer.server.port=3003"
      - "traefik.http.services.nango-connect.loadbalancer.server.port=3009"