version: "3.9"

networks:
  nango:
  proxy_net:
    external: true   # Coolify's external proxy network (same one keycloak uses)
    name: a8sk8cg0swg0ww0w0ogoowog  # map to the actual existing Docker network name

volumes:
  nango_db_data:

services:
  nango-db:
    image: postgres:16.0-alpine
    container_name: nango-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${NANGO_DB_USER:-nango}
      POSTGRES_PASSWORD: ${NANGO_DB_PASSWORD:-nango}
      POSTGRES_DB: ${NANGO_DB_NAME:-nango}
    volumes:
      - nango_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NANGO_DB_USER:-nango} -d ${NANGO_DB_NAME:-nango}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - nango

  nango-redis:
    image: redis:7.2.4
    container_name: nango-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - nango

  nango-server:
    image: nangohq/nango-server:hosted-0.67.0
    container_name: nango-server
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      nango-db:
        condition: service_healthy
      nango-redis:
        condition: service_healthy
    environment:
      SERVER_PORT: 3003
      NANGO_CONNECT_UI_PORT: 3009

      # Required
      NANGO_ENCRYPTION_KEY: ${NANGO_ENCRYPTION_KEY}

      # DB (internal hostnames)
      NANGO_DB_HOST: nango-db
      NANGO_DB_USER: nango
      NANGO_DB_PASSWORD: super-secret
      NANGO_DB_NAME: nango
      NANGO_DB_SSL: false
      NANGO_DB_POOL_MIN: 2
      NANGO_DB_POOL_MAX: 10
      RECORDS_DATABASE_URL: postgresql://nango:super-secret@nango-db:5432/nango

      # Public URLs (HTTPS via Traefik)
      NANGO_SERVER_URL: https://nango.csa.competera.com
      NANGO_PUBLIC_SERVER_URL: https://nango.csa.competera.com
      NANGO_PUBLIC_CONNECT_URL: https://nango.csa.competera.com/connect

      # Connect UI + websockets
      FLAG_SERVE_CONNECT_UI: true
      NANGO_SERVER_WEBSOCKETS_PATH: /socket

      # Dashboard auth
      FLAG_AUTH_ENABLED: true
      NANGO_DASHBOARD_USERNAME: admin
      NANGO_DASHBOARD_PASSWORD: change-me

      # Logging (optional ES)
      NANGO_LOGS_ENABLED: false
      NANGO_LOGS_ES_URL: http://nango-elasticsearch:9200
      NANGO_LOGS_ES_USER: ""
      NANGO_LOGS_ES_PWD: ""

      LOG_LEVEL: info
      CSP_REPORT_ONLY: true

    volumes:
      - ./packages/providers/providers.yaml:/packages/providers/providers.yaml:ro

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3003/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

    networks:
      - nango
      - proxy_net

    labels:
      - traefik.enable=true
      - traefik.docker.network=a8sk8cg0swg0ww0w0ogoowog
      - traefik.http.routers.nango.rule=Host(`nango.csa.competera.com`)
      - traefik.http.routers.nango.entrypoints=https
      - traefik.http.routers.nango.tls=true
      - traefik.http.routers.nango.tls.certresolver=letsencrypt
      - traefik.http.services.nango.loadbalancer.server.port=3003
